// Generated by gencpp from file ros_tutorial_msg/srvTestResponse.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MSG_MESSAGE_SRVTESTRESPONSE_H
#define ROS_TUTORIAL_MSG_MESSAGE_SRVTESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_tutorial_msg
{
template <class ContainerAllocator>
struct srvTestResponse_
{
  typedef srvTestResponse_<ContainerAllocator> Type;

  srvTestResponse_()
    : result(0)  {
    }
  srvTestResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvTestResponse_

typedef ::ros_tutorial_msg::srvTestResponse_<std::allocator<void> > srvTestResponse;

typedef boost::shared_ptr< ::ros_tutorial_msg::srvTestResponse > srvTestResponsePtr;
typedef boost::shared_ptr< ::ros_tutorial_msg::srvTestResponse const> srvTestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator1> & lhs, const ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator1> & lhs, const ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_tutorial_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "034a8e20d6a306665e3a5b340fab3f09";
  }

  static const char* value(const ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x034a8e20d6a30666ULL;
  static const uint64_t static_value2 = 0x5e3a5b340fab3f09ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_tutorial_msg/srvTestResponse";
  }

  static const char* value(const ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"\n"
;
  }

  static const char* value(const ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvTestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_tutorial_msg::srvTestResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TUTORIAL_MSG_MESSAGE_SRVTESTRESPONSE_H
