// Generated by gencpp from file ros_tutorial_msg/srvTest.msg
// DO NOT EDIT!


#ifndef ROS_TUTORIAL_MSG_MESSAGE_SRVTEST_H
#define ROS_TUTORIAL_MSG_MESSAGE_SRVTEST_H

#include <ros/service_traits.h>


#include <ros_tutorial_msg/srvTestRequest.h>
#include <ros_tutorial_msg/srvTestResponse.h>


namespace ros_tutorial_msg
{

struct srvTest
{

typedef srvTestRequest Request;
typedef srvTestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvTest
} // namespace ros_tutorial_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_tutorial_msg::srvTest > {
  static const char* value()
  {
    return "a7d7d7065d45755acef7d4dcf908162a";
  }

  static const char* value(const ::ros_tutorial_msg::srvTest&) { return value(); }
};

template<>
struct DataType< ::ros_tutorial_msg::srvTest > {
  static const char* value()
  {
    return "ros_tutorial_msg/srvTest";
  }

  static const char* value(const ::ros_tutorial_msg::srvTest&) { return value(); }
};


// service_traits::MD5Sum< ::ros_tutorial_msg::srvTestRequest> should match
// service_traits::MD5Sum< ::ros_tutorial_msg::srvTest >
template<>
struct MD5Sum< ::ros_tutorial_msg::srvTestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tutorial_msg::srvTest >::value();
  }
  static const char* value(const ::ros_tutorial_msg::srvTestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tutorial_msg::srvTestRequest> should match
// service_traits::DataType< ::ros_tutorial_msg::srvTest >
template<>
struct DataType< ::ros_tutorial_msg::srvTestRequest>
{
  static const char* value()
  {
    return DataType< ::ros_tutorial_msg::srvTest >::value();
  }
  static const char* value(const ::ros_tutorial_msg::srvTestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_tutorial_msg::srvTestResponse> should match
// service_traits::MD5Sum< ::ros_tutorial_msg::srvTest >
template<>
struct MD5Sum< ::ros_tutorial_msg::srvTestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_tutorial_msg::srvTest >::value();
  }
  static const char* value(const ::ros_tutorial_msg::srvTestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_tutorial_msg::srvTestResponse> should match
// service_traits::DataType< ::ros_tutorial_msg::srvTest >
template<>
struct DataType< ::ros_tutorial_msg::srvTestResponse>
{
  static const char* value()
  {
    return DataType< ::ros_tutorial_msg::srvTest >::value();
  }
  static const char* value(const ::ros_tutorial_msg::srvTestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TUTORIAL_MSG_MESSAGE_SRVTEST_H
